import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dadosFooter = {
  endereco: {
      nome: "Centro Administrativo Senador Doutor Teotônio Vilela",
      rua: "Av. Senador Teotônio Vilela, 4177 - Jardim América",
      cidade: "Vilhena - RO",
      cep: "78995-000",
  },
  contato: {
      email: "mailto:gabinete@vilhena.ro.gov.br",
      telefone: "tel:+5693919-7080",
      facebook: "https://www.facebook.com/municipiodevilhena/?locale=pt_BR",
      instagram: "https://www.instagram.com/municipiodevilhena/",
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <div className="relative z-20">
          <Header />
        </div>
          {children}
        <div className="relative z-20">
          <Footer endereco={dadosFooter.endereco} contato={dadosFooter.contato} />
        </div>
      </body>
    </html>
  );
}